/** Shared test fixture: the user's real Nov-2025 coach-sheet paste (verbatim).
 *  Used by workoutPaste tests and the liftRank integration test. */
// Build TSV lines without embedding literal tabs in the source.
export const L = (...cells: string[]) => cells.join('\t')

/** The user's real Nov-2025 paste (columns A–E of the coach sheet, verbatim). */
export const NOV_WEEK = [
  L('03/11/2025', '', '', '', '', ''),
  L('Monday', '', '', '', '', ''),
  L('Rear Delt Flyes', '55', '3', '12', '55 6r @10, 36.5 8r @10, 31.5 9r @10', ''),
  L('', '', '', '', '', ''),
  L('BTN Press', 'Load', 'Sets', 'Reps', '', ''),
  L('', '27.5', '3', '10', "Did 29kg, they don't have 1.25kg weights ", ''),
  L('', '', '', '', '', ''),
  L('Chest Supported Row', '50', '3', '10', '', ''),
  L('', '', '', '', '', ''),
  L('Spoto Bench Press', 'Load', 'Sets', 'Reps', '', ''),
  L('https://www.youtube.com/watch?v=2mn_NyAchgM', '65', '4', '7', 'This was so hard', ''),
  L('', '', '', '', '', ''),
  L('Lat Pulldown', '40.5', '3', '12', '', ''),
  L('', '', '', '', '', ''),
  L('Preacher Curl', '30lb', '3', '10', 'Last amrap 17', ''),
  L('', '', '', '', '', ''),
  L('Tricep Extension', '50lb', '3', '12', 'I switched to the extension machine', ''),
  L('', '', '', '', '', ''),
  L('Lateral Raise Machine', '22.5', '3', '12', '', ''),
  L('Tuesday', '', '', '', '', ''),
  L('Bike', '', '1', '5m', 'Done', ''),
  L('', '', '', '', '', ''),
  L('High Bar Squat', 'Load', 'Sets', 'Reps', '', ''),
  L('', '105', '1', '5', '', 'Not sure about @, but core unstable af'),
  L('', '', '', '', '', ''),
  L('3-2-0 Tempo Squat', '70', '3', '5', '', '72kg'),
  L('', '', '', '', '', ''),
  L('Deficit Paused Deadlift', 'Load', 'Sets', 'Reps', '', ''),
  L('Pause off the floor', '105', '7', '2', '60s rest', '123456'),
  L('', '', '', '', '', ''),
  L('Leg Extensions', '30', '3', '15', '12 @10, 8 @10, 8 @10', ''),
  L('', '', '', '', '', ''),
  L('Decline Sit Up', '5', '2', '10', 'Best back relief', ''),
  L('', '', '', '', '', ''),
  L('Back Raises', '15', '2', '15', '', ''),
  L('', '', '', '', '', ''),
  L('Cardio of Choice', '', '1', '2-30 min', 'Literally anything', ''),
  L('Wednesday', '', '', '', '', ''),
  L('Pause Bench Press', 'Load', 'Sets', 'Reps', '', ''),
  L('2-count puase on your chest', '70', '5', '5', '', ''),
  L('', '', '', '', '', ''),
  L('Assisted Chin Up', '15p', '3', '10', '', ''),
  L('', '', '', '', '', ''),
  L('Med Incline DB Bench Press', '25lb', '3', '20', '30lb 14 @8, 25lb 15 @9, ', ''),
  L('', '', '', '', '', ''),
  L('Bayesian Curl', '2p', '3', '12', '', ''),
  L('', '', '', '', '', ''),
  L('Tate Press', '25lb', '3', '12', '20, 25, 30 (30 too hard)', ''),
  L('', '', '', '', '', ''),
  L('EZ Bar Reverse Curl', '30lb', '2', '15', 'Never remove this', ''),
  L('Thursday'),
  L('Bike', '', '1', '5m', '', ''),
  L('', '', '', '', '', ''),
  L('Conventional Deadlift', 'Load', 'Sets', 'Reps', '', ''),
  L('', '125', '5', '3', '', ''),
  L('', '', '', '', '', ''),
  L('', '', '', '', '', ''),
  L('', '', '', '', '', ''),
  L('Hamstring Curl', '33kg', '3', '12', 'Idk why but I failed', ''),
  L('', '', '', '', '', ''),
  L('Bulgarian Split Squat', '55lb', '3', '8', '', ''),
  L('', '', '', '', '', ''),
  L('Cable Twists', '', '3', '10', '', ''),
  L('', '', '', '', '', ''),
  L('Cardio of Choice', '', '1', '2-30 min', 'Literally anything', ''),
  L('Friday', '', '', '', '', ''),
  L('Bike', '', '1', '5m', '', ''),
  L('', '', '', '', '', ''),
  L('Pogo Jumps', '', '2', '20', '', ''),
  L('', '', '', '', '', ''),
  L('Seated Vertical Jump', '', '3', '5', '', ''),
  L('', '', '', '', '', ''),
  L('HK Scoop Throw', '', '2', '15', '', ''),
  L('', '', '', '', '', ''),
  L('Seated Calf Raises', '', '3', '12', '', ''),
  L('', '', '', '', '', ''),
  L('Smith Side Bends', '', '3', '8', '', ''),
  L('', '', '', '', '', ''),
  L('Cardio of Choice', '', '1', '10-30 min', 'Literally anything'),
].join('\n')
